# Generated by Django 5.2.2 on 2025-08-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='listed_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='listed_owner_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='original_creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='original_creator_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='pp_dt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='pp_ez',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='pp_fl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='pp_hd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='pp_hr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='pp_ht',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='pp_nomod',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='rosu_timeseries',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='tagapplication',
            name='timestamp',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tagapplication',
            name='is_prediction',
            field=models.FloatField(default=False, help_text='Indicates if tag is predicted for this beatmap'),
        ),
    ]
