# Generated by Django 5.2.2 on 2025-08-13 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_beatmap_last_updated_beatmap_listed_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagapplication',
            name='is_prediction',
            field=models.BooleanField(default=False, help_text='Indicates if tag is predicted for this beatmap'),
        ),
    ]
