# Generated by Django 5.0 on 2024-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_alter_tagapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='drain',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
