# Generated by Django 5.0 on 2024-01-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0003_beatmap_drain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='osu_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
