# Generated by Django 5.2.2 on 2025-08-15 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0003_alter_apirequestlog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='method',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='path',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='beatmapset_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='creator',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='difficulty_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='favourite_count',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='last_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='listed_owner',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='listed_owner_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='mode',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='original_creator',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='original_creator_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='playcount',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='pp_dt',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='pp_ez',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='pp_fl',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='pp_hd',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='pp_hr',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='pp_ht',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='pp_nomod',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='downvotes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='upvotes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tagapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tagapplication',
            name='is_prediction',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if tag is predicted for this beatmap'),
        ),
        migrations.AlterField(
            model_name='tagapplication',
            name='prediction_confidence',
            field=models.FloatField(blank=True, db_index=True, default=0.0, help_text='Confidence level of the prediction', null=True),
        ),
        migrations.AlterField(
            model_name='tagdescriptionhistory',
            name='date_written',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='osu_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['timestamp', 'method'], name='echo_apireq_timesta_0f4442_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['user', 'timestamp'], name='echo_apireq_user_id_094091_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['path', 'timestamp'], name='echo_apireq_path_4c5fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['method', 'path'], name='echo_apireq_method_eb62cd_idx'),
        ),
        migrations.AddIndex(
            model_name='beatmap',
            index=models.Index(fields=['mode', 'difficulty_rating'], name='echo_beatma_mode_85cb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='beatmap',
            index=models.Index(fields=['status', 'difficulty_rating'], name='echo_beatma_status_4320cd_idx'),
        ),
        migrations.AddIndex(
            model_name='beatmap',
            index=models.Index(fields=['creator', 'status'], name='echo_beatma_creator_2b82e8_idx'),
        ),
        migrations.AddIndex(
            model_name='beatmap',
            index=models.Index(fields=['playcount', 'difficulty_rating'], name='echo_beatma_playcou_7483d8_idx'),
        ),
        migrations.AddIndex(
            model_name='beatmap',
            index=models.Index(fields=['favourite_count', 'difficulty_rating'], name='echo_beatma_favouri_a73e62_idx'),
        ),
        migrations.AddIndex(
            model_name='beatmap',
            index=models.Index(fields=['last_updated', 'status'], name='echo_beatma_last_up_31b768_idx'),
        ),
        migrations.AddIndex(
            model_name='beatmap',
            index=models.Index(fields=['title', 'artist'], name='echo_beatma_title_aae31b_idx'),
        ),
        migrations.AddIndex(
            model_name='beatmap',
            index=models.Index(fields=['artist', 'title'], name='echo_beatma_artist_21bbfb_idx'),
        ),
        migrations.AddIndex(
            model_name='customtoken',
            index=models.Index(fields=['user', 'created'], name='echo_custom_user_id_0c8dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['upvotes', 'downvotes'], name='echo_tag_upvotes_6df435_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_recommended', 'upvotes'], name='echo_tag_is_reco_148ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_locked', 'upvotes'], name='echo_tag_is_lock_cc05bb_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name', 'is_recommended'], name='echo_tag_name_d63671_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['beatmap', 'tag'], name='echo_tagapp_beatmap_973fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['user', 'beatmap'], name='echo_tagapp_user_id_330fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['tag', 'user'], name='echo_tagapp_tag_id_c1fc66_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['is_prediction'], name='echo_tagapp_is_pred_363926_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['created_at', 'is_prediction'], name='echo_tagapp_created_a7d710_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['beatmap', 'is_prediction'], name='echo_tagapp_beatmap_67bfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['tag', 'is_prediction'], name='echo_tagapp_tag_id_46bec1_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['prediction_confidence', 'is_prediction'], name='echo_tagapp_predict_a22b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['user', 'created_at'], name='echo_tagapp_user_id_576179_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['beatmap', 'created_at'], name='echo_tagapp_beatmap_8fac48_idx'),
        ),
        migrations.AddIndex(
            model_name='tagdescriptionhistory',
            index=models.Index(fields=['tag', 'date_written'], name='echo_tagdes_tag_id_951b09_idx'),
        ),
        migrations.AddIndex(
            model_name='tagdescriptionhistory',
            index=models.Index(fields=['author', 'date_written'], name='echo_tagdes_author__e81350_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['banned', 'osu_id'], name='echo_userpr_banned_ec4fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['tag', 'vote_type'], name='echo_vote_tag_id_83aa2d_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['timestamp', 'vote_type'], name='echo_vote_timesta_5ff1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'timestamp'], name='echo_vote_user_id_f0d328_idx'),
        ),
    ]
