# Generated by Django 5.0.2 on 2024-03-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0004_alter_userprofile_osu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='osu_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
