# Generated by Django 5.2.2 on 2025-08-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0004_alter_apirequestlog_method_alter_apirequestlog_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='status_code',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
