# Generated by Django 5.0.2 on 2024-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0005_beatmap_mode_alter_userprofile_osu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
