# Generated by Django 5.2.2 on 2025-08-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0006_remove_beatmap_rosu_timeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='listed_owner_edited_by_owner',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='listed_owner_is_manual_override',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
