# Generated by Django 5.2.2 on 2025-08-29 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0007_beatmap_listed_owner_edited_by_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tagapplication',
            name='true_negative',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates this tag is an explicit true negative for this beatmap'),
        ),
        migrations.AlterUniqueTogether(
            name='tagapplication',
            unique_together={('tag', 'beatmap', 'user', 'true_negative', 'is_prediction')},
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['true_negative'], name='echo_tagapp_true_ne_9af9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['created_at', 'true_negative'], name='echo_tagapp_created_23120d_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['beatmap', 'true_negative'], name='echo_tagapp_beatmap_c0823a_idx'),
        ),
        migrations.AddIndex(
            model_name='tagapplication',
            index=models.Index(fields=['tag', 'true_negative'], name='echo_tagapp_tag_id_473eea_idx'),
        ),
    ]
