# Generated by Django 5.0.2 on 2024-09-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0007_alter_beatmap_artist_alter_beatmap_beatmap_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customapikey',
            name='key_name',
            field=models.CharField(blank=True, default='Key Name', max_length=255),
        ),
    ]
