# Generated by Django 5.0.2 on 2024-09-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0008_alter_customapikey_key_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customapikey',
            name='key_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
