# Generated by Django 5.2.2 on 2025-09-06 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0008_alter_tagapplication_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('mapping_genre', 'Mapping Genre'), ('pattern_type', 'Pattern Type'), ('metadata', 'Metadata'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.CreateModel(
            name='TagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='echo.tag')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='echo.tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', through='echo.TagRelation', through_fields=('child', 'parent'), to='echo.tag'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['category'], name='echo_tag_categor_8c419f_idx'),
        ),
        migrations.AddIndex(
            model_name='tagrelation',
            index=models.Index(fields=['parent', 'child'], name='echo_tagrel_parent__dab3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tagrelation',
            index=models.Index(fields=['child', 'parent'], name='echo_tagrel_child_i_30a6ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tagrelation',
            unique_together={('parent', 'child')},
        ),
    ]
