# Generated by Django 5.0.2 on 2024-10-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0009_alter_customapikey_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='beatmapset_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
