# Generated by Django 5.2.2 on 2025-09-06 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0009_tag_category_tagrelation_tag_parents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_category_display', models.CharField(choices=[('none', 'No Categories'), ('color', 'Color Coding'), ('lists', 'Separate Lists')], db_index=True, default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tag_category_display'], name='echo_userse_tag_cat_abf661_idx'), models.Index(fields=['user', 'tag_category_display'], name='echo_userse_user_id_4fc0f8_idx')],
            },
        ),
    ]

