# Generated by Django 5.2.2 on 2025-09-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0010_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='max_combo',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
