# Generated by Django 5.0.2 on 2024-10-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0010_beatmap_beatmapset_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAPIKey',
        ),
    ]
