# Generated by Django 5.2.2 on 2025-09-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0011_beatmap_max_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='group_related_tags',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_ar',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_bpm',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_cs',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_favourites',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_genres',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_hp',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_length',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_od',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_playcount',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_pp_calculator',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_pp_dt',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_pp_ez',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_pp_fl',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_pp_hd',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_pp_hr',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_pp_ht',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_pp_nm',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_star_rating',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_year',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
