# Generated by Django 5.2.2 on 2025-10-31 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0012_usersettings_group_related_tags_usersettings_show_ar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='Search', max_length=255)),
                ('query', models.CharField(blank=True, default='', max_length=1000)),
                ('params_json', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='echo_saveds_user_id_705542_idx'), models.Index(fields=['user', 'updated_at'], name='echo_saveds_user_id_c58546_idx'), models.Index(fields=['user', 'title'], name='echo_saveds_user_id_2163cd_idx')],
            },
        ),
    ]
