# Generated by Django 5.2.2 on 2025-11-15 08:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0013_savedsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('beatmap_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('search_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='echo_analyt_created_7b3071_idx'), models.Index(fields=['client_id', 'created_at'], name='echo_analyt_client__297952_idx'), models.Index(fields=['action', 'created_at'], name='echo_analyt_action_6bcbaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('query', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, null=True)),
                ('results_count', models.IntegerField(blank=True, null=True)),
                ('sort', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('predicted_mode', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('flags', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='echo_analyt_created_356c53_idx'), models.Index(fields=['client_id', 'created_at'], name='echo_analyt_client__63e20c_idx'), models.Index(fields=['sort', 'created_at'], name='echo_analyt_sort_6c0ed4_idx'), models.Index(fields=['predicted_mode', 'created_at'], name='echo_analyt_predict_c3ed7f_idx')],
            },
        ),
    ]
