# Generated by Django 5.0.2 on 2024-10-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0013_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description_author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
