# Generated by Django 5.2.2 on 2025-11-17 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0014_analyticsclickevent_analyticssearchevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='mode',
            field=models.CharField(choices=[('std', 'Standard'), ('taiko', 'Taiko'), ('catch', 'Catch'), ('mania', 'Mania')], db_index=True, default='std', max_length=16),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['mode'], name='echo_tag_mode_58c1a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'mode'), name='unique_tag_name_mode'),
        ),
    ]
