# Generated by Django 5.2.2 on 2025-11-27 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0015_tag_mode_alter_tag_name_tag_echo_tag_mode_58c1a7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManiaKeyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_mania_keys',
            field=models.CharField(db_index=True, default='any', max_length=16),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_mode',
            field=models.CharField(choices=[('osu', 'osu!'), ('taiko', 'Taiko'), ('catch', 'Catch the Beat'), ('mania', 'osu!mania')], db_index=True, default='osu', max_length=16),
        ),
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['default_mode'], name='echo_userse_default_ef0641_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['default_mania_keys'], name='echo_userse_default_9d4208_idx'),
        ),
    ]
