# Generated by Django 5.2.2 on 2026-01-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0016_maniakeyoption_usersettings_default_mania_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='shown_in_search',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
