# Generated by Django 5.0.2 on 2024-10-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
            ('echo', '0016_alter_userprofile_user'),
            ('echo', '0017_tag_downvotes_tag_is_locked_tag_upvotes_and_more'),
    ]

    operations = [
    ]