# Generated by Django 5.2.2 on 2026-01-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0017_beatmap_shown_in_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyActiveUserCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['hour'], name='echo_hourly_hour_b7e234_idx'), models.Index(fields=['updated_at'], name='echo_hourly_updated_c59891_idx')],
            },
        ),
    ]
