# Generated by Django 5.0.2 on 2024-10-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0017_tag_downvotes_tag_is_locked_tag_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
