# Generated by Django 5.2.2 on 2026-01-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0019_hourlyactiveusercount_breakdown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HourlyActiveUserCount',
        ),
        migrations.AddField(
            model_name='analyticsclickevent',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='analyticsclickevent',
            name='logged_in_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='analyticssearchevent',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='analyticssearchevent',
            name='logged_in_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='analyticsclickevent',
            index=models.Index(fields=['logged_in_user_id', 'created_at'], name='echo_analyt_logged__f92e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsclickevent',
            index=models.Index(fields=['is_staff', 'created_at'], name='echo_analyt_is_staf_cd6170_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssearchevent',
            index=models.Index(fields=['logged_in_user_id', 'created_at'], name='echo_analyt_logged__89266d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssearchevent',
            index=models.Index(fields=['is_staff', 'created_at'], name='echo_analyt_is_staf_3c262c_idx'),
        ),
    ]
