                      
# Generated by Django 5.0.2 on 2024-10-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0017_tag_downvotes_tag_is_locked_tag_upvotes_and_more'),
        ('echo', '0019_alter_tag_description_author'),
    ]

    operations = [
    ]


