# Generated by Django 5.0.2 on 2024-10-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0019_userprofile_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
