                      
# Generated by Django 5.0.2 on 2024-10-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0016_alter_tag_description_author'),
        ('echo', '0018_beatmap_status'),
        ('echo', '0020_merge_20241020_2053'),
    ]

    operations = [
    ]



