# Generated by Django 5.0.2 on 2024-10-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0021_tagdescriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='favourites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='playcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
