                      
# Generated by Django 5.0.2 on 2024-10-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0021_merge_20241020_2233'),
        ('echo', '0021_tagdescriptionhistory'),
    ]

    operations = [
    ]


