# Generated by Django 5.2.2 on 2026-09-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0022_delete_ppweightindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank_at_last_login',
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text='osu! global rank captured from the player API at last login.',
                null=True,
                verbose_name='Rank at last login',
            ),
        ),
    ]
