                      
# Generated by Django 5.0.2 on 2024-10-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0022_merge_20241025_0713'),
        ('echo', '0023_rename_favourites_beatmap_favourite_count'),
    ]

    operations = [
    ]


