# Generated by Django 5.0.2 on 2024-11-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0023_rename_favourites_beatmap_favourite_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='beatmap',
            name='genres',
            field=models.ManyToManyField(blank=True, to='echo.genre'),
        ),
    ]
