# Generated by Django 5.0.2 on 2024-11-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0024_genre_beatmap_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hiddenuser',
            field=models.BooleanField(default=False),
        ),
    ]
