                      
# Generated by Django 5.0.2 on 2024-11-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0024_genre_beatmap_genres'),
        ('echo', '0024_merge_20241028_2134'),
    ]

    operations = [
    ]

