# Generated by Django 5.0.2 on 2024-11-03 16:10

import django.db.models.deletion
import echo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0025_merge_20241103_1610'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description_author',
            field=models.ForeignKey(blank=True, default=echo.models.get_default_author, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_descriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]



