                      
# Generated by Django 5.0.2 on 2024-11-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0025_userprofile_hiddenuser'),
        ('echo', '0026_alter_tag_description_author'),
    ]

    operations = [
    ]

