# Generated by Django 5.0.2 on 2025-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0027_merge_20241105_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hiddenuser',
        ),
        migrations.AddField(
            model_name='tag',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
