# Generated by Django 4.2.6 on 2024-01-09 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatmap_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('version', models.CharField(blank=True, max_length=1000, null=True)),
                ('artist', models.CharField(blank=True, max_length=1000, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('total_length', models.IntegerField(blank=True, null=True)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('cs', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('ar', models.FloatField(blank=True, null=True)),
                ('difficulty_rating', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osu_id', models.CharField(max_length=100, unique=True)),
                ('profile_pic_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beatmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.beatmap')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.userprofile')),
            ],
            options={
                'unique_together': {('tag', 'beatmap', 'user')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='beatmaps',
            field=models.ManyToManyField(blank=True, related_name='tags', through='echo.TagApplication', to='echo.beatmap'),
        ),
    ]
