# Generated by Django 5.0 on 2023-12-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='beatmaps',
        ),
        migrations.AddField(
            model_name='beatmap',
            name='tags',
            field=models.ManyToManyField(related_name='beatmaps', to='echo.tag'),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='beatmap_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
