# Generated by Django 5.0 on 2023-12-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_remove_tag_beatmaps_beatmap_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='ar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='cs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='difficulty_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='hp_drain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='total_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='beatmap_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
