# Generated by Django 5.0 on 2023-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0003_beatmap_accuracy_beatmap_ar_beatmap_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmap',
            name='artist',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='beatmaps', to='echo.tag'),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
