# Generated by Django 5.0 on 2023-12-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0004_alter_beatmap_artist_alter_beatmap_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatmap',
            name='hp_drain',
        ),
        migrations.AddField(
            model_name='beatmap',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
