# Generated by Django 5.0 on 2023-12-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0005_remove_beatmap_hp_drain_beatmap_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='version',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
